### ISSUE TITLE
How to detect loss of network connection client-side in Chrome

### ISSUE THREAD

**Issue by mbech** [taoensso/sente#259] opened 2016-08-18 21:31 UTC
I'm having difficulty identifying when the websocket connection is down in Chrome.  I've looked through the docs and closed issues (some similarities to #230), but wasn't able to find a solution or insights into this particular issue.  I hope to confirm that I'm not overlooking an existing Sente feature/option that could help.
## Scenario:

Server deployed on Heroku, client logs in, websocket established/first-open, successfully sending messages back/forth.  Manually disable wifi on client, cutting the connection.
## Expected behavior (both Safari and Firefox):

Within a few seconds (~2-5) the `chsk-state` updates to reflect that the connection is no longer `:open?`.  My `add-watch` on `chsk-state` picks up the change and renders a notification to the user.  Sente begins trying to reconnect every few seconds (longer and longer pauses between attempts).  Once the network connection is back up, Sente reestablishes a websocket on next retry attempt.
## Unexpected actual behavior (Chrome):

No change to `chsk-state` occurs, at least in the 5 minutes I've let it sit after disabling wifi.  No event-msgs or errors/warnings appear to be thrown.  Once the network is back up, websocket is reestablished and works, but I haven't been able to find anything to watch/capture to inform the client when it's disconnected.

Using latest Chrome `Version 52.0.2743.116 (64-bit)` on OSX El Capitan 10.11.6
## Notes:

After researching, it seems this may be due to Chrome not throwing an "onClose" event when the connection dies, as opposed to Firefox/Safari which do throw that event (which I think Sente captures and reflects in the `chsk-state`)?

To get around it, I've considered setting up a ping/pong loop from client to server that fires every few seconds, and assume the connection is down if the client misses a few pongs in a row.  But I figured it was worth asking if I overlooked something before building out that workaround, especially since keeping an eye on `chsk-state` works so great in Firefox/Safari.

**Comment by ptaoussanis** [comment] 2016-08-19 03:24
Hi there. Thanks for the clear report, that's very welcome.

Just have my hands full today so haven't confirmed, but think you've identified a bug here related to #230.

Basically: #230 addressed the problem on the server side, and looks like we'll need an equivalent strategy on the client end to reliably identify these kinds of sudden disconnects across all browsers/devices. Didn't realise Chrome behaved this way.

Since we already have the server broadcasting pings at the necessary interval, we just need to mod the client with a simple timer to check if it's received any comms from the server w/in a timeout window.

Should be a simple fix, just fully occupied for the next week or two. Will try get to this asap.

>  I've considered setting up a ping/pong loop from client to server that fires every few seconds, and assume the connection is down if the client misses a few pongs in a row.

That sounds reasonable as a workaround so long.

Cheers!

**Comment by ptaoussanis** [comment] 2016-08-19 03:27
Quick note if you're not against running a fork so long- it might be easier for you to just use the built-in pings. You'll need to fork to make them available to your app:

https://github.com/ptaoussanis/sente/blob/ab45ef8839b0df17acd88cc2fcc992963e57b1c1/src/taoensso/sente.cljc#L1044

**Comment by mbech** [comment] 2016-08-19 19:43
Sounds good.  Thanks for confirming that I wasn't overlooking an existing config or other solution for this particular situation.

I'll read through the current Sente `ws-ping` keep-alive code more closely.  If adding a "pong" server response there makes sense I'll create a fork, otherwise it should be straightforward to add to my existing app as a standard `cshk-send!`/`event-msg-handler` set on a few second interval.

Thank you again for the timely response.  This is the first project I've used Sente in and it's been a great experience (especially with the help of the awesome readme and all the examples).

**Comment by ptaoussanis** [comment] 2016-08-20 03:13
Please note that a pong response isn't what you want since when the connection's down, the client won't receive the ping (pong response).

Had a free moment yesterday so quickly sketched out one approach at https://github.com/ptaoussanis/sente/commit/7ef597103b2c4005155428aef17c9553ef8cbb9f

Entirely untested, but may give you a starting point if you want to do your own pings. Basically, just need to send a client->server ping every x seconds if there haven't been any other messages sent or received in that time. The server can ignore the ping, the point would be for the client to attempt a send that will help it identify a broken connection.

**Comment by ptaoussanis** [comment] 2016-08-31 04:46
Have pushed `[com.taoensso/sente "1.11.0-alpha3"] to Clojars which adds a client-side :ws-kalive-ms option (defaults to 20s).

Haven't had an opportunity to test yet, please let me know if this addresses your issue? Thanks!

**Comment by ptaoussanis** [comment] 2016-09-08 04:45
Any update on this? May I close?

**Comment by ptaoussanis** [comment] 2016-09-16 03:54
Will assume that this is resolved.

**Comment by rafd** [comment] 2017-02-27 01:39
In response for the request for feedback (https://github.com/ptaoussanis/sente/issues/259#issuecomment-245492379). Here is a report on some tests I've done:  

Summary:

- adding `:ws-kalive-ms` back to the client (https://github.com/ptaoussanis/sente/commit/d925b66a7adae600ca2dc84cededc4302a010f11 )  
 has made it _possible_ to detect abnormal disconnects in Chrome, but the feature is currently limited: it takes ~50s to detect a disconnect (even with a `:ws-kalive-ms` set to 5s)

- `:ws-kalive-ms` has no effect on Firefox or Safari, which trigger a websocket disconnect event independent of messages sent

- Chrome seems to trigger a disconnect only on the first message sent that is ~45s after the network actually disconnects

If the intent of `:ws-kalive-ms` is to provide an upper-bound on "time to detect disconnect", then the implementation will need to be updated.

Given the behaviour of Chrome, one way to implement such a bound in sente would be for the client to `ping` every X seconds, and then trigger a disconnect if no `pong` response is detected within Y seconds.

-----

Below are my test results for Chrome, Firefox and Safari: 

Browser | Version | Time to Detect Disconnect
----|-----|----
Chrome | 56.0.2924.87 | ~50s
Firefox | 51.0.1 | ~10s
Safari | 9.1.2 | ~0s (immediate)

 - tested on OS X 10.11.6 , MBPr Late 2013
 - client's `:ws-kalive-ms` set to `5000`

Before disconnecting, I can see the `:chsk/ws-ping` events in Chrome's inspector every 5 sec (as expected). When I turn WiFi off, the ping events continue every 5 seconds, but a disconnect is only triggered after ~50 seconds. 

With a `:ws-kalive-ms` of 30 seconds, Chrome seems to only trigger on the next websocket message ~45 seconds after the actual connection is dropped.

I believe each browser triggers the websocket close event under different conditions:
 
  - Safari seems to be listening to the OS-level network adapter state, and immediately closes the socket when the network is disabled (independent of any outgoing messages)
  - Chrome waits until the OS-level TCP timeout [1] [2] (~45 seconds on my machine) and then triggers the websocket close on the next attempted outgoing websocket message (the explained rationale is that if the network connection is resumed within the TCP timeout window, the websocket messages will still go through)
  - Firefox seems to close after ~10s (independent of any outgoing messages). (Conjecture: like Chrome, they may be waiting for TCP timeout, but use a shorter timeout window)

A visual summary of what seems to be happening:
<img width="737" alt="screen shot 2017-02-27 at 10 01 18 am" src="https://cloud.githubusercontent.com/assets/89664/23345566/a990b764-fcd3-11e6-8a32-dbca69c8b11f.png">



[1] https://bugs.chromium.org/p/chromium/issues/detail?id=197841
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=76358

**Comment by danielcompton** [comment] 2017-02-27 19:13
Thanks for the testing, where did you test it? On localhost, or over the internet? The reason I ask is that I could imagine Safari might have different behaviour over the internet than on localhost if it's listening to the OS network adapter.

**Comment by rafd** [comment] 2017-02-27 22:13
@danielcompton I tested over the internet (both deployed to a VPS, and also running in dev on a different machine on the same network).

I will do some tests in a few hours where the server's network connection drops (vs. my previous tests, which were all for the client).

**Comment by ptaoussanis** [comment] 2017-02-27 22:43
Hey Rafal, thanks a lot for the detailed info! Don't have an opportunity to look into this right away, but will try make it a priority next time I'm doing a batch of open-source work.

Any additional tests/details/conclusions you (or others) can put together in the meantime would of course be a huge help!

Cheers :-)

**Comment by rafd** [comment] 2017-02-28 03:37
I did some testing on disconnect-detection with the network being disabled on the server-side: 

https://docs.google.com/spreadsheets/d/1OVXbNPN2-TNRBQvnmhKK8IXM_vQ0NiD7ptUEijpQWeo/edit?usp=sharing

Notably:
  - each browser takes 30s+ to detect a disconnection
  - the time is not consistent between browsers (chrome ~55s, firefox: ~45s, safari: ~25s)
  - the time-to-detect varies greatly (occasionally taking up to 120s) (ie. high variance)
  - for the same browser, disconnect detection is not consistent (except for Safari)

Later tonight I will add:
  - server-side abnormal disconnect w/ 600s keepalive ping (effectively, without keepalive)
  - redo tests for client-side abnormal disconnect to be more rigorous, like the server-side tests (5 runs per browser, at 0.5s, 30s and 600s keepalive)

**Comment by rafd** [comment] 2017-03-02 03:16
I've updated my post above w/ new data. 

With the client-side `:ws-keep-alive`, each browser will eventually notice a disconnect (which wasn't the case before). 

However, the time to detect varies greatly between browsers (and even for the same browser), so, it would be nice for sente users to have a way to optionally set their own, more aggressive and standardized threshold. However, this is a further extension, so, perhaps it deservers its own issue?

**Comment by ptaoussanis** [comment] 2017-03-24 18:27
Sorry for the delay handling this, have been swamped lately. Will make this my first priority next time I've got some time to batch work on Sente!

**Comment by ptaoussanis** [comment] 2023-02-24 11:19
This should hopefully be addressed by the forthcoming v1.18 release.

Will ping when the first public alpha is out, and keep this issue open until there's general consensus that the issue is adequately resolved.

Apologies for the long delay on this!

**Closed** 2023-07-31 15:30 UTC
Labels: bug, input welcome, can close?
